// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Toaster } from "react-hot-toast";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//         cz-shortcut-listen="true"
//       >
//         <Toaster />
//         {children}
//       </body>
//     </html>
//   );
// }






"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { usePathname } from "next/navigation";
import PublicNavbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  // Define the dashboard segments
  // If the URL starts with any of these, we hide the Public Navbar
  const hidePublicNav = 
    pathname.startsWith("/admin") || 
    pathname.startsWith("/donor") || 
    pathname.startsWith("/receiver");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black`}
        cz-shortcut-listen="true"
      >
        <Toaster position="top-center" reverseOrder={false} />
        
        {/* Render PublicNavbar only on non-dashboard routes */}
        {!hidePublicNav && <PublicNavbar />}

        <main className="min-h-screen">
          {children}
        </main>

        {/* Optional: Add a Public Footer only on non-dashboard routes */}
        {!hidePublicNav && (
          <footer className="py-10 border-t border-gray-100 bg-gray-50 text-center">
            <p className="text-gray-400 text-sm font-medium">
              © 2025 LifeFlow Management System. Saving lives through technology.
            </p>
          </footer>
        )}
      </body>
    </html>
  );
}